### ISSUE TITLE
Backslashes show up as %2F, domain not included in resulting URL

### ISSUE THREAD

**Issue by suqoshi** [timbooo/traktforalfred#4]
I had to add "http://trakt.tv/" to the Open URL Object for the workflow to even contact the trakt.tv website.

But I get a 404 every time I try to view a movie on the website using this workflow because the backslashes show up as %2F.

Can you look into resolving this?

**Comment by timbooo** [comment]
Please revert what you've done in the Open URL Object in the Alfred workflow configuration. Open the workflow directory (Alfred Workflows -> Right-click workflow -> Show in Finder) and replace the traktforalfred.php file with the latest.

**Comment by suqoshi** [comment]
That works, but why not update it here?
https://timbooo.github.io/traktforalfred/

**Comment by timbooo** [comment]
I don't want to create a new release because the current release is partly broken (due to the switch from Trakt to a new API). Thus it would take a great effort to update but since I personally don't have the time I only provided that quick fix for you (and possibly others).
Anyways I'm planning to update the workflow to work with Trakt API v2 in the future.
